version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew clean test --parallel --stacktrace --no-daemon
      - run:
          name: Run Code Coverage
          command: ./gradlew jacocoTestReport
      - run:
          name: Upload Code Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
             - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results